name: DUILGMc
version: 0.4.3
load: STARTUP
main: fr.kestrel.duilgmc.Main
api-version: 1.17
commands:
  send:
    description: Send the holding item to another player
  skills:
    description: View skills
  extractench:
    description: Extract the enchants of an holding item